version: "3.9"

services:
  kong:
    image: kong:3.8
    container_name: kong-gateway

    env_file:
      - .env

    volumes:
      - ./kong/kong.yml:/kong/declarative/kong.yml

    ports:
      - "8000:8000" # Proxy
      - "8001:8001" # Admin API
      - "8443:8443"
      - "8444:8444"

    restart: unless-stopped
